# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTextEdit, QWidget)

from ui.gl_image_widget import ImageGLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(945, 742)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButtonConnectCam1 = QPushButton(self.centralwidget)
        self.pushButtonConnectCam1.setObjectName(u"pushButtonConnectCam1")
        self.pushButtonConnectCam1.setGeometry(QRect(30, 380, 101, 31))
        self.pushButtonConnectCam2 = QPushButton(self.centralwidget)
        self.pushButtonConnectCam2.setObjectName(u"pushButtonConnectCam2")
        self.pushButtonConnectCam2.setGeometry(QRect(540, 380, 101, 31))
        self.pushButtonDisconnectCam1 = QPushButton(self.centralwidget)
        self.pushButtonDisconnectCam1.setObjectName(u"pushButtonDisconnectCam1")
        self.pushButtonDisconnectCam1.setGeometry(QRect(30, 420, 101, 31))
        self.pushButtonDisconnectCam2 = QPushButton(self.centralwidget)
        self.pushButtonDisconnectCam2.setObjectName(u"pushButtonDisconnectCam2")
        self.pushButtonDisconnectCam2.setGeometry(QRect(540, 420, 101, 31))
        self.lineEditSerialCam1 = QLineEdit(self.centralwidget)
        self.lineEditSerialCam1.setObjectName(u"lineEditSerialCam1")
        self.lineEditSerialCam1.setGeometry(QRect(140, 10, 161, 21))
        self.labelSerialNumCam1 = QLabel(self.centralwidget)
        self.labelSerialNumCam1.setObjectName(u"labelSerialNumCam1")
        self.labelSerialNumCam1.setGeometry(QRect(30, 10, 111, 16))
        font = QFont()
        font.setPointSize(10)
        self.labelSerialNumCam1.setFont(font)
        self.labelSerialNumCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSerialNumCam2 = QLabel(self.centralwidget)
        self.labelSerialNumCam2.setObjectName(u"labelSerialNumCam2")
        self.labelSerialNumCam2.setGeometry(QRect(540, 10, 111, 16))
        self.labelSerialNumCam2.setFont(font)
        self.labelSerialNumCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditSerialCam2_2 = QLineEdit(self.centralwidget)
        self.lineEditSerialCam2_2.setObjectName(u"lineEditSerialCam2_2")
        self.lineEditSerialCam2_2.setGeometry(QRect(650, 10, 161, 24))
        self.doubleSpinBoxExposureCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxExposureCam1.setObjectName(u"doubleSpinBoxExposureCam1")
        self.doubleSpinBoxExposureCam1.setGeometry(QRect(330, 380, 81, 31))
        self.doubleSpinBoxExposureCam1.setMaximum(100000.000000000000000)
        self.doubleSpinBoxExposureCam1.setValue(50.000000000000000)
        self.doubleSpinBoxExposureCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxExposureCam2.setObjectName(u"doubleSpinBoxExposureCam2")
        self.doubleSpinBoxExposureCam2.setGeometry(QRect(840, 380, 81, 31))
        self.doubleSpinBoxExposureCam2.setMaximum(100000.000000000000000)
        self.doubleSpinBoxExposureCam2.setValue(50.000000000000000)
        self.labelExposureTimeCam1 = QLabel(self.centralwidget)
        self.labelExposureTimeCam1.setObjectName(u"labelExposureTimeCam1")
        self.labelExposureTimeCam1.setGeometry(QRect(150, 385, 101, 21))
        self.labelExposureTimeCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelExposureTimeCam2 = QLabel(self.centralwidget)
        self.labelExposureTimeCam2.setObjectName(u"labelExposureTimeCam2")
        self.labelExposureTimeCam2.setGeometry(QRect(650, 385, 111, 21))
        self.labelExposureTimeCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelGainCam1 = QLabel(self.centralwidget)
        self.labelGainCam1.setObjectName(u"labelGainCam1")
        self.labelGainCam1.setGeometry(QRect(170, 425, 49, 21))
        font1 = QFont()
        font1.setPointSize(11)
        self.labelGainCam1.setFont(font1)
        self.labelGainCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxGainCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxGainCam1.setObjectName(u"doubleSpinBoxGainCam1")
        self.doubleSpinBoxGainCam1.setGeometry(QRect(330, 420, 81, 31))
        self.doubleSpinBoxGainCam1.setMaximum(100000.000000000000000)
        self.doubleSpinBoxGainCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxGainCam2.setObjectName(u"doubleSpinBoxGainCam2")
        self.doubleSpinBoxGainCam2.setGeometry(QRect(840, 420, 81, 31))
        self.doubleSpinBoxGainCam2.setMaximum(100000.000000000000000)
        self.labelGainCam2 = QLabel(self.centralwidget)
        self.labelGainCam2.setObjectName(u"labelGainCam2")
        self.labelGainCam2.setGeometry(QRect(680, 425, 49, 21))
        self.labelGainCam2.setFont(font1)
        self.labelGainCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelFpsCam1 = QLabel(self.centralwidget)
        self.labelFpsCam1.setObjectName(u"labelFpsCam1")
        self.labelFpsCam1.setGeometry(QRect(170, 465, 49, 21))
        self.labelFpsCam1.setFont(font1)
        self.labelFpsCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelFpsCam2 = QLabel(self.centralwidget)
        self.labelFpsCam2.setObjectName(u"labelFpsCam2")
        self.labelFpsCam2.setGeometry(QRect(680, 465, 49, 21))
        self.labelFpsCam2.setFont(font1)
        self.labelFpsCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxFpsCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxFpsCam1.setObjectName(u"doubleSpinBoxFpsCam1")
        self.doubleSpinBoxFpsCam1.setGeometry(QRect(330, 460, 81, 31))
        self.doubleSpinBoxFpsCam1.setMaximum(100000.000000000000000)
        self.doubleSpinBoxFpsCam1.setValue(100.000000000000000)
        self.doubleSpinBoxFpsCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxFpsCam2.setObjectName(u"doubleSpinBoxFpsCam2")
        self.doubleSpinBoxFpsCam2.setGeometry(QRect(840, 460, 81, 31))
        self.doubleSpinBoxFpsCam2.setMaximum(100000.000000000000000)
        self.doubleSpinBoxFpsCam2.setValue(100.000000000000000)
        self.spinBoxWidthCam1 = QSpinBox(self.centralwidget)
        self.spinBoxWidthCam1.setObjectName(u"spinBoxWidthCam1")
        self.spinBoxWidthCam1.setGeometry(QRect(80, 40, 81, 25))
        self.spinBoxWidthCam1.setMaximumSize(QSize(81, 25))
        self.spinBoxWidthCam1.setMaximum(10000)
        self.spinBoxWidthCam1.setValue(512)
        self.labelSerialWidthCam1 = QLabel(self.centralwidget)
        self.labelSerialWidthCam1.setObjectName(u"labelSerialWidthCam1")
        self.labelSerialWidthCam1.setGeometry(QRect(30, 40, 51, 20))
        self.labelSerialWidthCam1.setFont(font)
        self.labelSerialWidthCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBoxHeightCam1 = QSpinBox(self.centralwidget)
        self.spinBoxHeightCam1.setObjectName(u"spinBoxHeightCam1")
        self.spinBoxHeightCam1.setGeometry(QRect(220, 40, 81, 25))
        self.spinBoxHeightCam1.setMaximum(10000)
        self.spinBoxHeightCam1.setValue(512)
        self.labelSerialHeightCam1 = QLabel(self.centralwidget)
        self.labelSerialHeightCam1.setObjectName(u"labelSerialHeightCam1")
        self.labelSerialHeightCam1.setGeometry(QRect(170, 40, 51, 20))
        self.labelSerialHeightCam1.setFont(font)
        self.labelSerialHeightCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBoxHeightCam2 = QSpinBox(self.centralwidget)
        self.spinBoxHeightCam2.setObjectName(u"spinBoxHeightCam2")
        self.spinBoxHeightCam2.setGeometry(QRect(730, 40, 81, 25))
        self.spinBoxHeightCam2.setMaximum(10000)
        self.spinBoxHeightCam2.setValue(512)
        self.spinBoxWidthCam2 = QSpinBox(self.centralwidget)
        self.spinBoxWidthCam2.setObjectName(u"spinBoxWidthCam2")
        self.spinBoxWidthCam2.setGeometry(QRect(590, 40, 81, 25))
        self.spinBoxWidthCam2.setMaximum(10000)
        self.spinBoxWidthCam2.setValue(512)
        self.labelSerialWidthCam2 = QLabel(self.centralwidget)
        self.labelSerialWidthCam2.setObjectName(u"labelSerialWidthCam2")
        self.labelSerialWidthCam2.setGeometry(QRect(540, 40, 51, 20))
        self.labelSerialWidthCam2.setFont(font)
        self.labelSerialWidthCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSerialHeightCam2 = QLabel(self.centralwidget)
        self.labelSerialHeightCam2.setObjectName(u"labelSerialHeightCam2")
        self.labelSerialHeightCam2.setGeometry(QRect(680, 40, 51, 20))
        self.labelSerialHeightCam2.setFont(font)
        self.labelSerialHeightCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBoxOffsetYCam1 = QSpinBox(self.centralwidget)
        self.spinBoxOffsetYCam1.setObjectName(u"spinBoxOffsetYCam1")
        self.spinBoxOffsetYCam1.setGeometry(QRect(220, 70, 81, 25))
        self.spinBoxOffsetYCam1.setMaximum(10000)
        self.spinBoxOffsetXCam1 = QSpinBox(self.centralwidget)
        self.spinBoxOffsetXCam1.setObjectName(u"spinBoxOffsetXCam1")
        self.spinBoxOffsetXCam1.setGeometry(QRect(80, 70, 81, 25))
        self.spinBoxOffsetXCam1.setMaximum(10000)
        self.labelSerialOffsetXCam1 = QLabel(self.centralwidget)
        self.labelSerialOffsetXCam1.setObjectName(u"labelSerialOffsetXCam1")
        self.labelSerialOffsetXCam1.setGeometry(QRect(30, 70, 51, 20))
        self.labelSerialOffsetXCam1.setFont(font)
        self.labelSerialOffsetXCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSerialOffsetYCam1 = QLabel(self.centralwidget)
        self.labelSerialOffsetYCam1.setObjectName(u"labelSerialOffsetYCam1")
        self.labelSerialOffsetYCam1.setGeometry(QRect(170, 70, 51, 20))
        self.labelSerialOffsetYCam1.setFont(font)
        self.labelSerialOffsetYCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBoxOffsetXCam2 = QSpinBox(self.centralwidget)
        self.spinBoxOffsetXCam2.setObjectName(u"spinBoxOffsetXCam2")
        self.spinBoxOffsetXCam2.setGeometry(QRect(590, 70, 81, 25))
        self.spinBoxOffsetXCam2.setMaximum(10000)
        self.labelSerialOffsetYCam2 = QLabel(self.centralwidget)
        self.labelSerialOffsetYCam2.setObjectName(u"labelSerialOffsetYCam2")
        self.labelSerialOffsetYCam2.setGeometry(QRect(680, 70, 51, 20))
        self.labelSerialOffsetYCam2.setFont(font)
        self.labelSerialOffsetYCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSerialOffsetXCam2 = QLabel(self.centralwidget)
        self.labelSerialOffsetXCam2.setObjectName(u"labelSerialOffsetXCam2")
        self.labelSerialOffsetXCam2.setGeometry(QRect(540, 70, 51, 20))
        self.labelSerialOffsetXCam2.setFont(font)
        self.labelSerialOffsetXCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBoxOffsetYCam2 = QSpinBox(self.centralwidget)
        self.spinBoxOffsetYCam2.setObjectName(u"spinBoxOffsetYCam2")
        self.spinBoxOffsetYCam2.setGeometry(QRect(730, 70, 81, 25))
        self.spinBoxOffsetYCam2.setMaximum(10000)
        self.checkBoxCenterROICam1 = QCheckBox(self.centralwidget)
        self.checkBoxCenterROICam1.setObjectName(u"checkBoxCenterROICam1")
        self.checkBoxCenterROICam1.setGeometry(QRect(320, 70, 81, 31))
        self.checkBoxCenterROICam2 = QCheckBox(self.centralwidget)
        self.checkBoxCenterROICam2.setObjectName(u"checkBoxCenterROICam2")
        self.checkBoxCenterROICam2.setGeometry(QRect(820, 70, 81, 31))
        self.labelPixelFormatCam1 = QLabel(self.centralwidget)
        self.labelPixelFormatCam1.setObjectName(u"labelPixelFormatCam1")
        self.labelPixelFormatCam1.setGeometry(QRect(150, 540, 101, 21))
        self.labelPixelFormatCam1.setFont(font1)
        self.labelPixelFormatCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBoxPixelFormatCam1 = QComboBox(self.centralwidget)
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.addItem("")
        self.comboBoxPixelFormatCam1.setObjectName(u"comboBoxPixelFormatCam1")
        self.comboBoxPixelFormatCam1.setGeometry(QRect(260, 540, 151, 21))
        self.comboBoxPixelFormatCam1.setFont(font)
        self.labelPixelFormatCam2 = QLabel(self.centralwidget)
        self.labelPixelFormatCam2.setObjectName(u"labelPixelFormatCam2")
        self.labelPixelFormatCam2.setGeometry(QRect(660, 540, 101, 16))
        self.labelPixelFormatCam2.setFont(font1)
        self.labelPixelFormatCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelExtensionCam1 = QLabel(self.centralwidget)
        self.labelExtensionCam1.setObjectName(u"labelExtensionCam1")
        self.labelExtensionCam1.setGeometry(QRect(150, 570, 101, 21))
        self.labelExtensionCam1.setFont(font1)
        self.labelExtensionCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBoxExtensionCam1 = QComboBox(self.centralwidget)
        self.comboBoxExtensionCam1.addItem("")
        self.comboBoxExtensionCam1.addItem("")
        self.comboBoxExtensionCam1.addItem("")
        self.comboBoxExtensionCam1.addItem("")
        self.comboBoxExtensionCam1.setObjectName(u"comboBoxExtensionCam1")
        self.comboBoxExtensionCam1.setGeometry(QRect(260, 570, 151, 21))
        self.comboBoxExtensionCam1.setFont(font)
        self.comboBoxExtensionCam2 = QComboBox(self.centralwidget)
        self.comboBoxExtensionCam2.addItem("")
        self.comboBoxExtensionCam2.addItem("")
        self.comboBoxExtensionCam2.addItem("")
        self.comboBoxExtensionCam2.addItem("")
        self.comboBoxExtensionCam2.setObjectName(u"comboBoxExtensionCam2")
        self.comboBoxExtensionCam2.setGeometry(QRect(770, 570, 151, 21))
        self.comboBoxExtensionCam2.setFont(font)
        self.labelExtensionCam2 = QLabel(self.centralwidget)
        self.labelExtensionCam2.setObjectName(u"labelExtensionCam2")
        self.labelExtensionCam2.setGeometry(QRect(660, 570, 101, 21))
        self.labelExtensionCam2.setFont(font1)
        self.labelExtensionCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButtonSelectSaveFolderCam1 = QPushButton(self.centralwidget)
        self.pushButtonSelectSaveFolderCam1.setObjectName(u"pushButtonSelectSaveFolderCam1")
        self.pushButtonSelectSaveFolderCam1.setGeometry(QRect(140, 600, 111, 21))
        self.pushButtonSelectSaveFolderCam1.setFont(font)
        self.pushButtonSelectSaveFolderCam2 = QPushButton(self.centralwidget)
        self.pushButtonSelectSaveFolderCam2.setObjectName(u"pushButtonSelectSaveFolderCam2")
        self.pushButtonSelectSaveFolderCam2.setGeometry(QRect(650, 600, 111, 21))
        self.pushButtonSelectSaveFolderCam2.setFont(font)
        self.lineEditSaveFolderCam1 = QLineEdit(self.centralwidget)
        self.lineEditSaveFolderCam1.setObjectName(u"lineEditSaveFolderCam1")
        self.lineEditSaveFolderCam1.setGeometry(QRect(260, 600, 151, 21))
        self.lineEditSaveFolderCam2 = QLineEdit(self.centralwidget)
        self.lineEditSaveFolderCam2.setObjectName(u"lineEditSaveFolderCam2")
        self.lineEditSaveFolderCam2.setGeometry(QRect(770, 600, 151, 24))
        self.pushButtonStartRecordCam1 = QPushButton(self.centralwidget)
        self.pushButtonStartRecordCam1.setObjectName(u"pushButtonStartRecordCam1")
        self.pushButtonStartRecordCam1.setGeometry(QRect(30, 510, 101, 41))
        self.pushButtonStopRecordCam1 = QPushButton(self.centralwidget)
        self.pushButtonStopRecordCam1.setObjectName(u"pushButtonStopRecordCam1")
        self.pushButtonStopRecordCam1.setGeometry(QRect(30, 560, 101, 41))
        self.pushButtonStopRecordCam2 = QPushButton(self.centralwidget)
        self.pushButtonStopRecordCam2.setObjectName(u"pushButtonStopRecordCam2")
        self.pushButtonStopRecordCam2.setGeometry(QRect(540, 560, 101, 41))
        self.pushButtonStartRecordCam2 = QPushButton(self.centralwidget)
        self.pushButtonStartRecordCam2.setObjectName(u"pushButtonStartRecordCam2")
        self.pushButtonStartRecordCam2.setGeometry(QRect(540, 510, 101, 41))
        self.textEditLogCam1 = QTextEdit(self.centralwidget)
        self.textEditLogCam1.setObjectName(u"textEditLogCam1")
        self.textEditLogCam1.setGeometry(QRect(70, 660, 341, 31))
        self.labelLogCam1 = QLabel(self.centralwidget)
        self.labelLogCam1.setObjectName(u"labelLogCam1")
        self.labelLogCam1.setGeometry(QRect(30, 660, 41, 21))
        self.labelLogCam1.setFont(font1)
        self.labelLogCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.textEditLogCam2 = QTextEdit(self.centralwidget)
        self.textEditLogCam2.setObjectName(u"textEditLogCam2")
        self.textEditLogCam2.setGeometry(QRect(580, 660, 341, 31))
        self.labelLogCam2 = QLabel(self.centralwidget)
        self.labelLogCam2.setObjectName(u"labelLogCam2")
        self.labelLogCam2.setGeometry(QRect(540, 660, 41, 21))
        self.labelLogCam2.setFont(font1)
        self.labelLogCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBoxExposureCam1 = QComboBox(self.centralwidget)
        self.comboBoxExposureCam1.addItem("")
        self.comboBoxExposureCam1.addItem("")
        self.comboBoxExposureCam1.addItem("")
        self.comboBoxExposureCam1.setObjectName(u"comboBoxExposureCam1")
        self.comboBoxExposureCam1.setGeometry(QRect(260, 380, 61, 31))
        self.comboBoxExposureCam1.setFont(font)
        self.comboBoxGainCam1 = QComboBox(self.centralwidget)
        self.comboBoxGainCam1.addItem("")
        self.comboBoxGainCam1.addItem("")
        self.comboBoxGainCam1.addItem("")
        self.comboBoxGainCam1.setObjectName(u"comboBoxGainCam1")
        self.comboBoxGainCam1.setGeometry(QRect(260, 420, 61, 31))
        self.comboBoxGainCam1.setFont(font)
        self.comboBoxGainCam2 = QComboBox(self.centralwidget)
        self.comboBoxGainCam2.addItem("")
        self.comboBoxGainCam2.addItem("")
        self.comboBoxGainCam2.addItem("")
        self.comboBoxGainCam2.setObjectName(u"comboBoxGainCam2")
        self.comboBoxGainCam2.setGeometry(QRect(770, 420, 61, 31))
        self.comboBoxGainCam2.setFont(font)
        self.comboBoxExposureCam2 = QComboBox(self.centralwidget)
        self.comboBoxExposureCam2.addItem("")
        self.comboBoxExposureCam2.addItem("")
        self.comboBoxExposureCam2.addItem("")
        self.comboBoxExposureCam2.setObjectName(u"comboBoxExposureCam2")
        self.comboBoxExposureCam2.setGeometry(QRect(770, 380, 61, 31))
        self.comboBoxExposureCam2.setFont(font)
        self.comboBoxFpsCam1 = QComboBox(self.centralwidget)
        self.comboBoxFpsCam1.addItem("")
        self.comboBoxFpsCam1.addItem("")
        self.comboBoxFpsCam1.setObjectName(u"comboBoxFpsCam1")
        self.comboBoxFpsCam1.setGeometry(QRect(260, 460, 61, 31))
        self.comboBoxFpsCam1.setFont(font)
        self.comboBoxFpsCam2 = QComboBox(self.centralwidget)
        self.comboBoxFpsCam2.addItem("")
        self.comboBoxFpsCam2.addItem("")
        self.comboBoxFpsCam2.setObjectName(u"comboBoxFpsCam2")
        self.comboBoxFpsCam2.setGeometry(QRect(770, 460, 61, 31))
        self.comboBoxFpsCam2.setFont(font)
        self.pushButtonStopRecordDualCams = QPushButton(self.centralwidget)
        self.pushButtonStopRecordDualCams.setObjectName(u"pushButtonStopRecordDualCams")
        self.pushButtonStopRecordDualCams.setGeometry(QRect(420, 240, 101, 41))
        self.pushButtonStartRecordDualCams = QPushButton(self.centralwidget)
        self.pushButtonStartRecordDualCams.setObjectName(u"pushButtonStartRecordDualCams")
        self.pushButtonStartRecordDualCams.setGeometry(QRect(420, 190, 101, 41))
        self.checkBoxSyncCheckCam1_2 = QCheckBox(self.centralwidget)
        self.checkBoxSyncCheckCam1_2.setObjectName(u"checkBoxSyncCheckCam1_2")
        self.checkBoxSyncCheckCam1_2.setGeometry(QRect(440, 110, 71, 22))
        font2 = QFont()
        font2.setPointSize(12)
        self.checkBoxSyncCheckCam1_2.setFont(font2)
        self.pushButtonHistogramCam1 = QPushButton(self.centralwidget)
        self.pushButtonHistogramCam1.setObjectName(u"pushButtonHistogramCam1")
        self.pushButtonHistogramCam1.setGeometry(QRect(419, 310, 101, 24))
        self.pushButtonHistogramCam2 = QPushButton(self.centralwidget)
        self.pushButtonHistogramCam2.setObjectName(u"pushButtonHistogramCam2")
        self.pushButtonHistogramCam2.setGeometry(QRect(420, 340, 101, 24))
        self.openGLWidgetImageCam1 = ImageGLWidget(self.centralwidget)
        self.openGLWidgetImageCam1.setObjectName(u"openGLWidgetImageCam1")
        self.openGLWidgetImageCam1.setGeometry(QRect(20, 100, 391, 271))
        self.openGLWidgetImageCam2 = ImageGLWidget(self.centralwidget)
        self.openGLWidgetImageCam2.setObjectName(u"openGLWidgetImageCam2")
        self.openGLWidgetImageCam2.setGeometry(QRect(530, 100, 391, 271))
        self.pushButtonLiveViewCam1 = QPushButton(self.centralwidget)
        self.pushButtonLiveViewCam1.setObjectName(u"pushButtonLiveViewCam1")
        self.pushButtonLiveViewCam1.setGeometry(QRect(310, 10, 101, 24))
        self.pushButtonLiveViewCam2 = QPushButton(self.centralwidget)
        self.pushButtonLiveViewCam2.setObjectName(u"pushButtonLiveViewCam2")
        self.pushButtonLiveViewCam2.setGeometry(QRect(820, 10, 101, 24))
        self.labelRecordingTimeCam1 = QLabel(self.centralwidget)
        self.labelRecordingTimeCam1.setObjectName(u"labelRecordingTimeCam1")
        self.labelRecordingTimeCam1.setGeometry(QRect(140, 500, 111, 31))
        self.labelRecordingTimeCam1.setFont(font1)
        self.labelRecordingTimeCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxRecordingTimeCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxRecordingTimeCam1.setObjectName(u"doubleSpinBoxRecordingTimeCam1")
        self.doubleSpinBoxRecordingTimeCam1.setGeometry(QRect(260, 500, 131, 31))
        self.doubleSpinBoxRecordingTimeCam1.setValue(0.100000000000000)
        self.labelRecordingTimeCam2 = QLabel(self.centralwidget)
        self.labelRecordingTimeCam2.setObjectName(u"labelRecordingTimeCam2")
        self.labelRecordingTimeCam2.setGeometry(QRect(650, 500, 111, 31))
        self.labelRecordingTimeCam2.setFont(font1)
        self.labelRecordingTimeCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxRecordingTimeCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxRecordingTimeCam2.setObjectName(u"doubleSpinBoxRecordingTimeCam2")
        self.doubleSpinBoxRecordingTimeCam2.setGeometry(QRect(770, 500, 131, 31))
        self.doubleSpinBoxRecordingTimeCam2.setValue(0.100000000000000)
        self.labelRecordingTimeUnitCam1 = QLabel(self.centralwidget)
        self.labelRecordingTimeUnitCam1.setObjectName(u"labelRecordingTimeUnitCam1")
        self.labelRecordingTimeUnitCam1.setGeometry(QRect(390, 510, 21, 16))
        self.labelRecordingTimeUnitCam1.setFont(font1)
        self.labelRecordingTimeUnitCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelRecordingTimeUnitCam1_2 = QLabel(self.centralwidget)
        self.labelRecordingTimeUnitCam1_2.setObjectName(u"labelRecordingTimeUnitCam1_2")
        self.labelRecordingTimeUnitCam1_2.setGeometry(QRect(900, 510, 21, 16))
        self.labelRecordingTimeUnitCam1_2.setFont(font1)
        self.labelRecordingTimeUnitCam1_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.checkBoxReverseXCam1 = QCheckBox(self.centralwidget)
        self.checkBoxReverseXCam1.setObjectName(u"checkBoxReverseXCam1")
        self.checkBoxReverseXCam1.setGeometry(QRect(320, 30, 77, 31))
        self.checkBoxReverseYCam1 = QCheckBox(self.centralwidget)
        self.checkBoxReverseYCam1.setObjectName(u"checkBoxReverseYCam1")
        self.checkBoxReverseYCam1.setGeometry(QRect(320, 50, 77, 31))
        self.checkBoxReverseXCam2 = QCheckBox(self.centralwidget)
        self.checkBoxReverseXCam2.setObjectName(u"checkBoxReverseXCam2")
        self.checkBoxReverseXCam2.setGeometry(QRect(820, 30, 77, 31))
        self.checkBoxReverseYCam2 = QCheckBox(self.centralwidget)
        self.checkBoxReverseYCam2.setObjectName(u"checkBoxReverseYCam2")
        self.checkBoxReverseYCam2.setGeometry(QRect(820, 50, 77, 31))
        self.pushButtonCaptureOneFrameCam1_2 = QPushButton(self.centralwidget)
        self.pushButtonCaptureOneFrameCam1_2.setObjectName(u"pushButtonCaptureOneFrameCam1_2")
        self.pushButtonCaptureOneFrameCam1_2.setGeometry(QRect(420, 140, 101, 41))
        self.comboBoxPixelFormatCam2 = QComboBox(self.centralwidget)
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.addItem("")
        self.comboBoxPixelFormatCam2.setObjectName(u"comboBoxPixelFormatCam2")
        self.comboBoxPixelFormatCam2.setGeometry(QRect(770, 540, 151, 21))
        self.comboBoxPixelFormatCam2.setFont(font)
        self.pushButtonCaptureOneFrameCam1 = QPushButton(self.centralwidget)
        self.pushButtonCaptureOneFrameCam1.setObjectName(u"pushButtonCaptureOneFrameCam1")
        self.pushButtonCaptureOneFrameCam1.setGeometry(QRect(30, 460, 101, 41))
        self.pushButtonCaptureOneFrameCam2 = QPushButton(self.centralwidget)
        self.pushButtonCaptureOneFrameCam2.setObjectName(u"pushButtonCaptureOneFrameCam2")
        self.pushButtonCaptureOneFrameCam2.setGeometry(QRect(540, 460, 101, 41))
        self.comboBoxWhiteBalanceAutoCam1 = QComboBox(self.centralwidget)
        self.comboBoxWhiteBalanceAutoCam1.addItem("")
        self.comboBoxWhiteBalanceAutoCam1.addItem("")
        self.comboBoxWhiteBalanceAutoCam1.addItem("")
        self.comboBoxWhiteBalanceAutoCam1.setObjectName(u"comboBoxWhiteBalanceAutoCam1")
        self.comboBoxWhiteBalanceAutoCam1.setGeometry(QRect(350, 630, 61, 22))
        self.labelExtensionCam1_2 = QLabel(self.centralwidget)
        self.labelExtensionCam1_2.setObjectName(u"labelExtensionCam1_2")
        self.labelExtensionCam1_2.setGeometry(QRect(240, 630, 111, 21))
        font3 = QFont()
        font3.setPointSize(9)
        self.labelExtensionCam1_2.setFont(font3)
        self.labelExtensionCam1_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxBalanceRatioRedCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxBalanceRatioRedCam1.setObjectName(u"doubleSpinBoxBalanceRatioRedCam1")
        self.doubleSpinBoxBalanceRatioRedCam1.setGeometry(QRect(90, 630, 71, 22))
        self.doubleSpinBoxBalanceRatioRedCam1.setMaximum(10.000000000000000)
        self.doubleSpinBoxBalanceRatioRedCam1.setSingleStep(0.100000000000000)
        self.doubleSpinBoxBalanceRatioRedCam1.setValue(1.000000000000000)
        self.labelBalanceRatioCam1 = QLabel(self.centralwidget)
        self.labelBalanceRatioCam1.setObjectName(u"labelBalanceRatioCam1")
        self.labelBalanceRatioCam1.setGeometry(QRect(0, 620, 91, 31))
        self.labelBalanceRatioCam1.setFont(font)
        self.labelBalanceRatioCam1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBoxWhiteBalanceAutoCam2 = QComboBox(self.centralwidget)
        self.comboBoxWhiteBalanceAutoCam2.addItem("")
        self.comboBoxWhiteBalanceAutoCam2.addItem("")
        self.comboBoxWhiteBalanceAutoCam2.addItem("")
        self.comboBoxWhiteBalanceAutoCam2.setObjectName(u"comboBoxWhiteBalanceAutoCam2")
        self.comboBoxWhiteBalanceAutoCam2.setGeometry(QRect(860, 630, 61, 22))
        self.labelExtensionCam2_2 = QLabel(self.centralwidget)
        self.labelExtensionCam2_2.setObjectName(u"labelExtensionCam2_2")
        self.labelExtensionCam2_2.setGeometry(QRect(750, 630, 111, 21))
        self.labelExtensionCam2_2.setFont(font3)
        self.labelExtensionCam2_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxBalanceRatioBlueCam1 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxBalanceRatioBlueCam1.setObjectName(u"doubleSpinBoxBalanceRatioBlueCam1")
        self.doubleSpinBoxBalanceRatioBlueCam1.setGeometry(QRect(170, 630, 71, 22))
        self.doubleSpinBoxBalanceRatioBlueCam1.setMaximum(10.000000000000000)
        self.doubleSpinBoxBalanceRatioBlueCam1.setSingleStep(0.100000000000000)
        self.doubleSpinBoxBalanceRatioBlueCam1.setValue(1.000000000000000)
        self.labelBalanceRatioCam2 = QLabel(self.centralwidget)
        self.labelBalanceRatioCam2.setObjectName(u"labelBalanceRatioCam2")
        self.labelBalanceRatioCam2.setGeometry(QRect(510, 620, 91, 31))
        self.labelBalanceRatioCam2.setFont(font)
        self.labelBalanceRatioCam2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBoxBalanceRatioRedCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxBalanceRatioRedCam2.setObjectName(u"doubleSpinBoxBalanceRatioRedCam2")
        self.doubleSpinBoxBalanceRatioRedCam2.setGeometry(QRect(600, 630, 71, 22))
        self.doubleSpinBoxBalanceRatioRedCam2.setMaximum(10.000000000000000)
        self.doubleSpinBoxBalanceRatioRedCam2.setSingleStep(0.100000000000000)
        self.doubleSpinBoxBalanceRatioRedCam2.setValue(1.000000000000000)
        self.doubleSpinBoxBalanceRatioBlueCam2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxBalanceRatioBlueCam2.setObjectName(u"doubleSpinBoxBalanceRatioBlueCam2")
        self.doubleSpinBoxBalanceRatioBlueCam2.setGeometry(QRect(680, 630, 71, 22))
        self.doubleSpinBoxBalanceRatioBlueCam2.setMaximum(10.000000000000000)
        self.doubleSpinBoxBalanceRatioBlueCam2.setSingleStep(0.100000000000000)
        self.doubleSpinBoxBalanceRatioBlueCam2.setValue(1.000000000000000)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 945, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButtonConnectCam1.setText(QCoreApplication.translate("MainWindow", u"Connect Cam1", None))
        self.pushButtonConnectCam2.setText(QCoreApplication.translate("MainWindow", u"Connect Cam2", None))
        self.pushButtonDisconnectCam1.setText(QCoreApplication.translate("MainWindow", u"Disconnect Cam1", None))
        self.pushButtonDisconnectCam2.setText(QCoreApplication.translate("MainWindow", u"Disconnect Cam2", None))
        self.lineEditSerialCam1.setText(QCoreApplication.translate("MainWindow", u"23152398", None))
        self.labelSerialNumCam1.setText(QCoreApplication.translate("MainWindow", u"Cam1 Serial Num", None))
        self.labelSerialNumCam2.setText(QCoreApplication.translate("MainWindow", u"Cam2 Serial Num", None))
        self.lineEditSerialCam2_2.setText(QCoreApplication.translate("MainWindow", u"23152404", None))
        self.labelExposureTimeCam1.setText(QCoreApplication.translate("MainWindow", u"Exposure Time [\u03bcs]", None))
        self.labelExposureTimeCam2.setText(QCoreApplication.translate("MainWindow", u"Exposure Time [\u03bcs]", None))
        self.labelGainCam1.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.labelGainCam2.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.labelFpsCam1.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.labelFpsCam2.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.labelSerialWidthCam1.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.labelSerialHeightCam1.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.labelSerialWidthCam2.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.labelSerialHeightCam2.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.labelSerialOffsetXCam1.setText(QCoreApplication.translate("MainWindow", u"OffsetX", None))
        self.labelSerialOffsetYCam1.setText(QCoreApplication.translate("MainWindow", u"OffsetY", None))
        self.labelSerialOffsetYCam2.setText(QCoreApplication.translate("MainWindow", u"OffsetY", None))
        self.labelSerialOffsetXCam2.setText(QCoreApplication.translate("MainWindow", u"OffsetX", None))
        self.checkBoxCenterROICam1.setText(QCoreApplication.translate("MainWindow", u"Center ROI", None))
        self.checkBoxCenterROICam2.setText(QCoreApplication.translate("MainWindow", u"Center ROI", None))
        self.labelPixelFormatCam1.setText(QCoreApplication.translate("MainWindow", u"Pixel Format", None))
        self.comboBoxPixelFormatCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"Mono8", None))
        self.comboBoxPixelFormatCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"BGR8", None))
        self.comboBoxPixelFormatCam1.setItemText(2, QCoreApplication.translate("MainWindow", u"BGRa8", None))
        self.comboBoxPixelFormatCam1.setItemText(3, QCoreApplication.translate("MainWindow", u"Mono16", None))
        self.comboBoxPixelFormatCam1.setItemText(4, QCoreApplication.translate("MainWindow", u"RGB8Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(5, QCoreApplication.translate("MainWindow", u"BayerRG8", None))
        self.comboBoxPixelFormatCam1.setItemText(6, QCoreApplication.translate("MainWindow", u"BayerGR8", None))
        self.comboBoxPixelFormatCam1.setItemText(7, QCoreApplication.translate("MainWindow", u"BayerRG16", None))
        self.comboBoxPixelFormatCam1.setItemText(8, QCoreApplication.translate("MainWindow", u"BayerGR16", None))
        self.comboBoxPixelFormatCam1.setItemText(9, QCoreApplication.translate("MainWindow", u"Mono10Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(10, QCoreApplication.translate("MainWindow", u"BayerRG10Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(11, QCoreApplication.translate("MainWindow", u"BayerGR10Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(12, QCoreApplication.translate("MainWindow", u"Mono12Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(13, QCoreApplication.translate("MainWindow", u"BayerRG12Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(14, QCoreApplication.translate("MainWindow", u"BayerGR12Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(15, QCoreApplication.translate("MainWindow", u"YUV411Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(16, QCoreApplication.translate("MainWindow", u"YUV422Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(17, QCoreApplication.translate("MainWindow", u"YUV444Packed", None))
        self.comboBoxPixelFormatCam1.setItemText(18, QCoreApplication.translate("MainWindow", u"Mono10p", None))
        self.comboBoxPixelFormatCam1.setItemText(19, QCoreApplication.translate("MainWindow", u"BayerRG10p", None))
        self.comboBoxPixelFormatCam1.setItemText(20, QCoreApplication.translate("MainWindow", u"BayerGR10p", None))
        self.comboBoxPixelFormatCam1.setItemText(21, QCoreApplication.translate("MainWindow", u"Mono12p", None))
        self.comboBoxPixelFormatCam1.setItemText(22, QCoreApplication.translate("MainWindow", u"BayerRG12p", None))
        self.comboBoxPixelFormatCam1.setItemText(23, QCoreApplication.translate("MainWindow", u"BayerGR12p", None))
        self.comboBoxPixelFormatCam1.setItemText(24, QCoreApplication.translate("MainWindow", u"YCbCr8", None))
        self.comboBoxPixelFormatCam1.setItemText(25, QCoreApplication.translate("MainWindow", u"YCbCr422_8", None))
        self.comboBoxPixelFormatCam1.setItemText(26, QCoreApplication.translate("MainWindow", u"YCbCr411_8", None))

        self.labelPixelFormatCam2.setText(QCoreApplication.translate("MainWindow", u"Pixel Format", None))
        self.labelExtensionCam1.setText(QCoreApplication.translate("MainWindow", u"Extension", None))
        self.comboBoxExtensionCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"png", None))
        self.comboBoxExtensionCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"bmp", None))
        self.comboBoxExtensionCam1.setItemText(2, QCoreApplication.translate("MainWindow", u"jpeg", None))
        self.comboBoxExtensionCam1.setItemText(3, QCoreApplication.translate("MainWindow", u"jpg", None))

        self.comboBoxExtensionCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"png", None))
        self.comboBoxExtensionCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"bmp", None))
        self.comboBoxExtensionCam2.setItemText(2, QCoreApplication.translate("MainWindow", u"jpeg", None))
        self.comboBoxExtensionCam2.setItemText(3, QCoreApplication.translate("MainWindow", u"jpg", None))

        self.labelExtensionCam2.setText(QCoreApplication.translate("MainWindow", u"Extension", None))
        self.pushButtonSelectSaveFolderCam1.setText(QCoreApplication.translate("MainWindow", u"Select Save Folder ", None))
        self.pushButtonSelectSaveFolderCam2.setText(QCoreApplication.translate("MainWindow", u"Select Save Folder ", None))
        self.lineEditSaveFolderCam1.setText("")
        self.lineEditSaveFolderCam2.setText("")
        self.pushButtonStartRecordCam1.setText(QCoreApplication.translate("MainWindow", u"Start Record", None))
        self.pushButtonStopRecordCam1.setText(QCoreApplication.translate("MainWindow", u"Stop Record", None))
        self.pushButtonStopRecordCam2.setText(QCoreApplication.translate("MainWindow", u"Stop Record", None))
        self.pushButtonStartRecordCam2.setText(QCoreApplication.translate("MainWindow", u"Start Record", None))
        self.labelLogCam1.setText(QCoreApplication.translate("MainWindow", u"Log", None))
        self.labelLogCam2.setText(QCoreApplication.translate("MainWindow", u"Log", None))
        self.comboBoxExposureCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxExposureCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxExposureCam1.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.comboBoxGainCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxGainCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxGainCam1.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.comboBoxGainCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxGainCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxGainCam2.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.comboBoxExposureCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxExposureCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxExposureCam2.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.comboBoxFpsCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.comboBoxFpsCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"Max", None))

        self.comboBoxFpsCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.comboBoxFpsCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"Max", None))

        self.pushButtonStopRecordDualCams.setText(QCoreApplication.translate("MainWindow", u"Stop Record", None))
        self.pushButtonStartRecordDualCams.setText(QCoreApplication.translate("MainWindow", u"Start Record", None))
        self.checkBoxSyncCheckCam1_2.setText(QCoreApplication.translate("MainWindow", u" Sync.", None))
        self.pushButtonHistogramCam1.setText(QCoreApplication.translate("MainWindow", u"Histogram Cam1", None))
        self.pushButtonHistogramCam2.setText(QCoreApplication.translate("MainWindow", u"Histogram Cam2", None))
        self.pushButtonLiveViewCam1.setText(QCoreApplication.translate("MainWindow", u"Live View", None))
        self.pushButtonLiveViewCam2.setText(QCoreApplication.translate("MainWindow", u"Live View", None))
        self.labelRecordingTimeCam1.setText(QCoreApplication.translate("MainWindow", u"Recording Time", None))
        self.labelRecordingTimeCam2.setText(QCoreApplication.translate("MainWindow", u"Recording Time", None))
        self.labelRecordingTimeUnitCam1.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.labelRecordingTimeUnitCam1_2.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.checkBoxReverseXCam1.setText(QCoreApplication.translate("MainWindow", u"Reverse X", None))
        self.checkBoxReverseYCam1.setText(QCoreApplication.translate("MainWindow", u"Reverse Y", None))
        self.checkBoxReverseXCam2.setText(QCoreApplication.translate("MainWindow", u"Reverse X", None))
        self.checkBoxReverseYCam2.setText(QCoreApplication.translate("MainWindow", u"Reverse Y", None))
        self.pushButtonCaptureOneFrameCam1_2.setText(QCoreApplication.translate("MainWindow", u"Capture 1 frame", None))
        self.comboBoxPixelFormatCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"Mono8", None))
        self.comboBoxPixelFormatCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"BGR8", None))
        self.comboBoxPixelFormatCam2.setItemText(2, QCoreApplication.translate("MainWindow", u"BGRa8", None))
        self.comboBoxPixelFormatCam2.setItemText(3, QCoreApplication.translate("MainWindow", u"Mono16", None))
        self.comboBoxPixelFormatCam2.setItemText(4, QCoreApplication.translate("MainWindow", u"RGB8Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(5, QCoreApplication.translate("MainWindow", u"BayerRG8", None))
        self.comboBoxPixelFormatCam2.setItemText(6, QCoreApplication.translate("MainWindow", u"BayerGR8", None))
        self.comboBoxPixelFormatCam2.setItemText(7, QCoreApplication.translate("MainWindow", u"BayerRG16", None))
        self.comboBoxPixelFormatCam2.setItemText(8, QCoreApplication.translate("MainWindow", u"BayerGR16", None))
        self.comboBoxPixelFormatCam2.setItemText(9, QCoreApplication.translate("MainWindow", u"Mono10Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(10, QCoreApplication.translate("MainWindow", u"BayerRG10Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(11, QCoreApplication.translate("MainWindow", u"BayerGR10Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(12, QCoreApplication.translate("MainWindow", u"Mono12Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(13, QCoreApplication.translate("MainWindow", u"BayerRG12Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(14, QCoreApplication.translate("MainWindow", u"BayerGR12Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(15, QCoreApplication.translate("MainWindow", u"YUV411Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(16, QCoreApplication.translate("MainWindow", u"YUV422Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(17, QCoreApplication.translate("MainWindow", u"YUV444Packed", None))
        self.comboBoxPixelFormatCam2.setItemText(18, QCoreApplication.translate("MainWindow", u"Mono10p", None))
        self.comboBoxPixelFormatCam2.setItemText(19, QCoreApplication.translate("MainWindow", u"BayerRG10p", None))
        self.comboBoxPixelFormatCam2.setItemText(20, QCoreApplication.translate("MainWindow", u"BayerGR10p", None))
        self.comboBoxPixelFormatCam2.setItemText(21, QCoreApplication.translate("MainWindow", u"Mono12p", None))
        self.comboBoxPixelFormatCam2.setItemText(22, QCoreApplication.translate("MainWindow", u"BayerRG12p", None))
        self.comboBoxPixelFormatCam2.setItemText(23, QCoreApplication.translate("MainWindow", u"BayerGR12p", None))
        self.comboBoxPixelFormatCam2.setItemText(24, QCoreApplication.translate("MainWindow", u"YCbCr8", None))
        self.comboBoxPixelFormatCam2.setItemText(25, QCoreApplication.translate("MainWindow", u"YCbCr422_8", None))
        self.comboBoxPixelFormatCam2.setItemText(26, QCoreApplication.translate("MainWindow", u"YCbCr411_8", None))

        self.pushButtonCaptureOneFrameCam1.setText(QCoreApplication.translate("MainWindow", u"Capture 1 frame", None))
        self.pushButtonCaptureOneFrameCam2.setText(QCoreApplication.translate("MainWindow", u"Capture 1 frame", None))
        self.comboBoxWhiteBalanceAutoCam1.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxWhiteBalanceAutoCam1.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxWhiteBalanceAutoCam1.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.labelExtensionCam1_2.setText(QCoreApplication.translate("MainWindow", u"White Balance Auto", None))
        self.labelBalanceRatioCam1.setText(QCoreApplication.translate("MainWindow", u"Balance Ratio \n"
"Red/Blue", None))
        self.comboBoxWhiteBalanceAutoCam2.setItemText(0, QCoreApplication.translate("MainWindow", u"Off", None))
        self.comboBoxWhiteBalanceAutoCam2.setItemText(1, QCoreApplication.translate("MainWindow", u"Once", None))
        self.comboBoxWhiteBalanceAutoCam2.setItemText(2, QCoreApplication.translate("MainWindow", u"Continuous", None))

        self.labelExtensionCam2_2.setText(QCoreApplication.translate("MainWindow", u"White Balance Auto", None))
        self.labelBalanceRatioCam2.setText(QCoreApplication.translate("MainWindow", u"Balance Ratio \n"
"Red/Blue", None))
    # retranslateUi

